<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bus extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bus_model');
    } 

    /*
     * Listing of bus
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('bus/index?');
        $config['total_rows'] = $this->Bus_model->get_all_bus_count();
        $this->pagination->initialize($config);

        $data['bus'] = $this->Bus_model->get_all_bus($params);
        
        $data['_view'] = 'bus/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bus
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('numPlaque','NumPlaque','required');
		$this->form_validation->set_rules('marqueBus','MarqueBus','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'numPlaque' => $this->input->post('numPlaque'),
				'marqueBus' => $this->input->post('marqueBus'),
				'libelleBus' => $this->input->post('libelleBus'),
				'nombreSiege' => $this->input->post('nombreSiege'),
				'dateAjout' => date('Y-m-d H:i:s'),
            );
            
            $bus_id = $this->Bus_model->add_bus($params);
            redirect('bus/index');
        }
        else
        {            
            $data['_view'] = 'bus/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bus
     */
    function edit($bus_id)
    {   
        // check if the bus exists before trying to edit it
        $data['bus'] = $this->Bus_model->get_bus($bus_id);
        
        if(isset($data['bus']['bus_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('numPlaque','NumPlaque','required');
			$this->form_validation->set_rules('marqueBus','MarqueBus','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'numPlaque' => $this->input->post('numPlaque'),
					'marqueBus' => $this->input->post('marqueBus'),
					'libelleBus' => $this->input->post('libelleBus'),
					'nombreSiege' => $this->input->post('nombreSiege'),
			
                );

                $this->Bus_model->update_bus($bus_id,$params);            
                redirect('bus/index');
            }
            else
            {
                $data['_view'] = 'bus/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bus you are trying to edit does not exist.');
    } 

    /*
     * Deleting bus
     */
    function remove($bus_id)
    {
        $bus = $this->Bus_model->get_bus($bus_id);

        // check if the bus exists before trying to delete it
        if(isset($bus['bus_id']))
        {
            $this->Bus_model->delete_bus($bus_id);
            redirect('bus/index');
        }
        else
            show_error('The bus you are trying to delete does not exist.');
    }
    
}
