<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chauffeur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get chauffeur by chauff_id
     */
    function get_chauffeur($chauff_id)
    {
        return $this->db->get_where('tb_bm_chauffeurs',array('chauff_id'=>$chauff_id))->row_array();
    }
    
    /*
     * Get all chauffeurs count
     */
    function get_all_chauffeurs_count()
    {
        $this->db->from('tb_bm_chauffeurs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all chauffeurs
     */
    function get_all_chauffeurs($params = array())
    {
        $this->db->order_by('chauff_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_bm_chauffeurs')->result_array();
    }
        
    /*
     * function to add new chauffeur
     */
    function add_chauffeur($params)
    {
        $this->db->insert('tb_bm_chauffeurs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update chauffeur
     */
    function update_chauffeur($chauff_id,$params)
    {
        $this->db->where('chauff_id',$chauff_id);
        return $this->db->update('tb_bm_chauffeurs',$params);
    }
    
    /*
     * function to delete chauffeur
     */
    function delete_chauffeur($chauff_id)
    {
        return $this->db->delete('tb_bm_chauffeurs',array('chauff_id'=>$chauff_id));
    }
}
