<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mecanicien_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mecanicien by mec_id
     */
    function get_mecanicien($mec_id)
    {
        return $this->db->get_where('tb_bm_mecaniciens',array('mec_id'=>$mec_id))->row_array();
    }
    
    /*
     * Get all mecaniciens count
     */
    function get_all_mecaniciens_count()
    {
        $this->db->from('tb_bm_mecaniciens');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all mecaniciens
     */
    function get_all_mecaniciens($params = array())
    {
        $this->db->order_by('mec_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_bm_mecaniciens')->result_array();
    }
        
    /*
     * function to add new mecanicien
     */
    function add_mecanicien($params)
    {
        $this->db->insert('tb_bm_mecaniciens',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mecanicien
     */
    function update_mecanicien($mec_id,$params)
    {
        $this->db->where('mec_id',$mec_id);
        return $this->db->update('tb_bm_mecaniciens',$params);
    }
    
    /*
     * function to delete mecanicien
     */
    function delete_mecanicien($mec_id)
    {
        return $this->db->delete('tb_bm_mecaniciens',array('mec_id'=>$mec_id));
    }
}
