<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mouvement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mouvement by mvm_id
     */
    function get_mouvement($mvm_id)
    {
        return $this->db->get_where('tb_bm_mouvements',array('mvm_id'=>$mvm_id))->row_array();
    }
    
    /*
     * Get all mouvements count
     */
    function get_all_mouvements_count()
    {
        $this->db->from('tb_bm_mouvements');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all mouvements
     */
    function get_all_mouvements($params = array())
    {
        $this->db->order_by('mvm_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_bm_mouvements')->result_array();
    }
        
    /*
     * function to add new mouvement
     */
    function add_mouvement($params)
    {
        $this->db->insert('tb_bm_mouvements',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mouvement
     */
    function update_mouvement($mvm_id,$params)
    {
        $this->db->where('mvm_id',$mvm_id);
        return $this->db->update('tb_bm_mouvements',$params);
    }
    
    /*
     * function to delete mouvement
     */
    function delete_mouvement($mvm_id)
    {
        return $this->db->delete('tb_bm_mouvements',array('mvm_id'=>$mvm_id));
    }
}
